jdk: oraclejdk7
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - ./gradlew build test
after_failure:
  - cat /home/travis/build/longdivision/hex/app/build/outputs/lint-results.html
